# USA Presidential Election data analysis

The objective of this analysis is to gain insights in to the US presidential elections over the years

Data source: https://electionlab.mit.edu/data
https://dataverse.harvard.edu/dataset.xhtml?persistentId=doi:10.7910/DVN/42MVDX

### Import libraries

In [1]:
import pandas as pd
import numpy as np

### Read data

In [2]:
df = pd.read_csv("1976-2020-president.csv")

In [3]:
df.head()

,year,state,state_po,state_fips,state_cen,state_ic,office,candidate,party_detailed,writein,candidatevotes,totalvotes,version,notes,party_simplified
0,1976,ALABAMA,AL,1,63,41,US PRESIDENT,"CARTER, JIMMY",DEMOCRAT,False,659170,1182850,20210113,NaN,DEMOCRAT
1,1976,ALABAMA,AL,1,63,41,US PRESIDENT,"FORD, GERALD",REPUBLICAN,False,504070,1182850,20210113,NaN,REPUBLICAN
2,1976,ALABAMA,AL,1,63,41,US PRESIDENT,"MADDOX, LESTER",AMERICAN INDEPENDENT PARTY,False,9198,1182850,20210113,NaN,OTHER
3,1976,ALABAMA,AL,1,63,41,US PRESIDENT,"BUBAR, BENJAMIN """"BEN""""",PROHIBITION,False,6669,1182850,20210113,NaN,OTHER
4,1976,ALABAMA,AL,1,63,41,US PRESIDENT,"HALL, GUS",COMMUNIST PARTY USE,False,1954,1182850,20210113,NaN,OTHER

### Initial exploration

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4287 entries, 0 to 4286
Data columns (total 15 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   year              4287 non-null   int64
 1   state             4287 non-null   object
 2   state_po          4287 non-null   object
 3   state_fips        4287 non-null   int64
 4   state_cen         4287 non-null   int64
 5   state_ic          4287 non-null   int64
 6   office            4287 non-null   object
 7   candidate         4000 non-null   object
 8   party_detailed    3831 non-null   object
 9   writein           4284 non-null   object
 10  candidatevotes    4287 non-null   int64
 11  totalvotes        4287 non-null   int64
 12  version           4287 non-null   int64
 13  notes             0 non-null      float64
 14  party_simplified  4287 non-null   object
dtypes: float64(1), int64(7), object(7)
memory usage: 502.5+ KB

In [5]:
df.describe()

,year,state_fips,state_cen,state_ic,candidatevotes,totalvotes,version,notes
count,4287.000000,4287.000000,4287.000000,4287.000000,4.287000e+03,4.287000e+03,4287.0,0.0
mean,1999.080942,28.616982,53.665034,39.754840,3.119076e+05,2.366924e+06,20210113.0,NaN
std,14.220014,15.616459,26.029189,22.772216,7.648011e+05,2.465008e+06,0.0,NaN
min,1976.000000,1.000000,11.000000,1.000000,0.000000e+00,1.235740e+05,20210113.0,NaN
25%,1988.000000,16.000000,33.000000,22.000000,1.177000e+03,6.522740e+05,20210113.0,NaN
50%,2000.000000,28.000000,53.000000,42.000000,7.499000e+03,1.569180e+06,20210113.0,NaN
75%,2012.000000,41.000000,81.000000,61.000000,1.992415e+05,3.033118e+06,20210113.0,NaN
max,2020.000000,56.000000,95.000000,82.000000,1.111025e+07,1.750088e+07,20210113.0,NaN

In [6]:
us_df = df[(df['party_detailed']== 'DEMOCRAT') | (df['party_detailed'] == 'REPUBLICAN')]
us_df.head()

,year,state,state_po,state_fips,state_cen,state_ic,office,candidate,party_detailed,writein,candidatevotes,totalvotes,version,notes,party_simplified
0,1976,ALABAMA,AL,1,63,41,US PRESIDENT,"CARTER, JIMMY",DEMOCRAT,False,659170,1182850,20210113,NaN,DEMOCRAT
1,1976,ALABAMA,AL,1,63,41,US PRESIDENT,"FORD, GERALD",REPUBLICAN,False,504070,1182850,20210113,NaN,REPUBLICAN
7,1976,ALASKA,AK,2,94,81,US PRESIDENT,"FORD, GERALD",REPUBLICAN,False,71555,123574,20210113,NaN,REPUBLICAN
8,1976,ALASKA,AK,2,94,81,US PRESIDENT,"CARTER, JIMMY",DEMOCRAT,False,44058,123574,20210113,NaN,DEMOCRAT
11,1976,ARIZONA,AZ,4,86,61,US PRESIDENT,"FORD, GERALD",REPUBLICAN,False,418642,742719,20210113,NaN,REPUBLICAN

In [7]:
us_df.aggregate('candidate')

0             CARTER, JIMMY
1              FORD, GERALD
7              FORD, GERALD
8             CARTER, JIMMY
11             FORD, GERALD
               ...
4264       TRUMP, DONALD J.
4267    BIDEN, JOSEPH R. JR
4268       TRUMP, DONALD J.
4280    BIDEN, JOSEPH R. JR
4281       TRUMP, DONALD J.
Name: candidate, Length: 1225, dtype: object

In [8]:
us_df.groupby(['candidate','year','state']).sum()#.agg('candidatevotes')

                                        state_fips  state_cen  state_ic  \
candidate           year state
BIDEN, JOSEPH R. JR 2020 ALABAMA                 1         63        41
                         ALASKA                  2         94        81
                         ARIZONA                 4         86        61
                         ARKANSAS                5         71        42
                         CALIFORNIA              6         93        71
...                                            ...        ...       ...
TRUMP, DONALD J.    2020 VIRGINIA               51         54        40
                         WASHINGTON             53         91        73
                         WEST VIRGINIA          54         55        56
                         WISCONSIN              55         35        25
                         WYOMING                56         83        68

                                        candidatevotes  totalvotes   version  \
candidate           year state
BIDEN, JOSEPH R. JR 2020 ALABAMA                849624     2323282  20210113
                         ALASKA                 153778      359530  20210113
                         ARIZONA               1672143     3387326  20210113
                         ARKANSAS               423932     1219069  20210113
                         CALIFORNIA           11110250    17500881  20210113
...                                                ...         ...       ...
TRUMP, DONALD J.    2020 VIRGINIA              1962430     4460524  20210113
                         WASHINGTON            1584651     4087631  20210113
                         WEST VIRGINIA          545382      794652  20210113
                         WISCONSIN             1610184     3298041  20210113
                         WYOMING                193559      278503  20210113

                                        notes
candidate           year state
BIDEN, JOSEPH R. JR 2020 ALABAMA          0.0
                         ALASKA           0.0
                         ARIZONA          0.0
                         ARKANSAS         0.0
                         CALIFORNIA       0.0
...                                       ...
TRUMP, DONALD J.    2020 VIRGINIA         0.0
                         WASHINGTON       0.0
                         WEST VIRGINIA    0.0
                         WISCONSIN        0.0
                         WYOMING          0.0

[1222 rows x 7 columns]

In [ ]:
us_