# USA Presidential Election data analysis

With a contentious and tight US Presidential Election coming up on November 5th 2024, the objective of this analysis is to gain insights in to the US presidential elections over the years.

### Document
<b>Author:</b> Sahan Fernando<br>
<b>Title:</b> USA Presidential Election data analysis<br>

### Data source

<b>Author:</b> MIT Election Data and Science Lab<br>
<b>Title:</b> U.S. President 1976â€“2020<br>
<b>URL: </b>https://doi.org/10.7910/DVN/42MVDX

### Import libraries

In [69]:
import pandas as pd
import numpy as np

### Read data

The data source is published as a CSV file named "1976-2020-president.csv"

In [70]:
df = pd.read_csv("1976-2020-president.csv")

In [71]:
df.head()

,year,state,state_po,state_fips,state_cen,state_ic,office,candidate,party_detailed,writein,candidatevotes,totalvotes,version,notes,party_simplified
0,1976,ALABAMA,AL,1,63,41,US PRESIDENT,"CARTER, JIMMY",DEMOCRAT,False,659170,1182850,20210113,NaN,DEMOCRAT
1,1976,ALABAMA,AL,1,63,41,US PRESIDENT,"FORD, GERALD",REPUBLICAN,False,504070,1182850,20210113,NaN,REPUBLICAN
2,1976,ALABAMA,AL,1,63,41,US PRESIDENT,"MADDOX, LESTER",AMERICAN INDEPENDENT PARTY,False,9198,1182850,20210113,NaN,OTHER
3,1976,ALABAMA,AL,1,63,41,US PRESIDENT,"BUBAR, BENJAMIN """"BEN""""",PROHIBITION,False,6669,1182850,20210113,NaN,OTHER
4,1976,ALABAMA,AL,1,63,41,US PRESIDENT,"HALL, GUS",COMMUNIST PARTY USE,False,1954,1182850,20210113,NaN,OTHER

### Initial exploration

In [72]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4287 entries, 0 to 4286
Data columns (total 15 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   year              4287 non-null   int64
 1   state             4287 non-null   object
 2   state_po          4287 non-null   object
 3   state_fips        4287 non-null   int64
 4   state_cen         4287 non-null   int64
 5   state_ic          4287 non-null   int64
 6   office            4287 non-null   object
 7   candidate         4000 non-null   object
 8   party_detailed    3831 non-null   object
 9   writein           4284 non-null   object
 10  candidatevotes    4287 non-null   int64
 11  totalvotes        4287 non-null   int64
 12  version           4287 non-null   int64
 13  notes             0 non-null      float64
 14  party_simplified  4287 non-null   object
dtypes: float64(1), int64(7), object(7)
memory usage: 502.5+ KB

In [73]:
df.describe()

,year,state_fips,state_cen,state_ic,candidatevotes,totalvotes,version,notes
count,4287.000000,4287.000000,4287.000000,4287.000000,4.287000e+03,4.287000e+03,4287.0,0.0
mean,1999.080942,28.616982,53.665034,39.754840,3.119076e+05,2.366924e+06,20210113.0,NaN
std,14.220014,15.616459,26.029189,22.772216,7.648011e+05,2.465008e+06,0.0,NaN
min,1976.000000,1.000000,11.000000,1.000000,0.000000e+00,1.235740e+05,20210113.0,NaN
25%,1988.000000,16.000000,33.000000,22.000000,1.177000e+03,6.522740e+05,20210113.0,NaN
50%,2000.000000,28.000000,53.000000,42.000000,7.499000e+03,1.569180e+06,20210113.0,NaN
75%,2012.000000,41.000000,81.000000,61.000000,1.992415e+05,3.033118e+06,20210113.0,NaN
max,2020.000000,56.000000,95.000000,82.000000,1.111025e+07,1.750088e+07,20210113.0,NaN

As described the data set appears to be clean with no glaring anomalies. The data ranges from 1976-2020 as informed by the dataset. <br>

<br>

In the dataset the parties of candidates are divided in to two columns "party_detailed" and "party_simplified". "party_detailed" column entails the names of all the parties enrolled in the Election including the 2 major parties along with independant party names. "party_simplified" attempts to simplify this information by isolating the names of the 2 major parties - Democrats and Republicans, and renaming other parties as "Others" and "libertarians"

In [74]:
print("Unique parties count: "+str(df['party_detailed'].unique().size))

print("Simplified parties count: "+str(df['party_simplified'].unique().size))

Unique parties count: 173
Simplified parties count: 4

Historically there have been members of 173 parties contesting in the Presidential elections.

In order to look at the election as a whole (not as a state-wise endevour), we will consolidate the dataset to the total number of votes garnered by each candidate along with the total votes cast is in each election cycle.

In [75]:
df.groupby(['candidate','year','party_detailed']).sum()

                                             state_fips  state_cen  state_ic  \
candidate           year party_detailed
ALEXANDER, STEWART  2012 SOCIALIST                   59        174       129
ALLEN, JONATHAN     2008 HEARTQUAKE '08               8         84        62
AMONDSON, GENE      2004 CONCERNS OF PEOPLE           8         84        62
                         PROHIBITION                 22         72        45
                    2008 PROHIBITION                 42        215       150
...                                                 ...        ...       ...
WRIGHT, MARGARET    1976 PEOPLE'S                    27         41        33
YIAMOUYIANNIS, JOHN 1992 INDEPENDENT                 22         72        45
YOUNGKEIT, LOUIE G. 1988 INDEPENDENT                 49         87        67
ZEIDLER, FRANK      1976 SOCIALIST                  189        227       172
                         SOCIALIST U.S.A.            19         42        31

                                             candidatevotes  totalvotes  \
candidate           year party_detailed
ALEXANDER, STEWART  2012 SOCIALIST                     4074    16624517
ALLEN, JONATHAN     2008 HEARTQUAKE '08                 348     2401361
AMONDSON, GENE      2004 CONCERNS OF PEOPLE             378     2129630
                         PROHIBITION                   1566     1943106
                    2008 PROHIBITION                    653    12752866
...                                                     ...         ...
WRIGHT, MARGARET    1976 PEOPLE'S                       635     1949931
YIAMOUYIANNIS, JOHN 1992 INDEPENDENT                    808     1790017
YOUNGKEIT, LOUIE G. 1988 INDEPENDENT                    372      647008
ZEIDLER, FRANK      1976 SOCIALIST                     5399     7779637
                         SOCIALIST U.S.A.               233     1279303

                                               version  notes
candidate           year party_detailed
ALEXANDER, STEWART  2012 SOCIALIST            60630339    0.0
ALLEN, JONATHAN     2008 HEARTQUAKE '08       20210113    0.0
AMONDSON, GENE      2004 CONCERNS OF PEOPLE   20210113    0.0
                         PROHIBITION          20210113    0.0
                    2008 PROHIBITION          60630339    0.0
...                                                ...    ...
WRIGHT, MARGARET    1976 PEOPLE'S             20210113    0.0
YIAMOUYIANNIS, JOHN 1992 INDEPENDENT          20210113    0.0
YOUNGKEIT, LOUIE G. 1988 INDEPENDENT          20210113    0.0
ZEIDLER, FRANK      1976 SOCIALIST           101050565    0.0
                         SOCIALIST U.S.A.     20210113    0.0

[501 rows x 7 columns]

In [76]:
#as_index will be set to false to consolidate the indexing.
us_total_votes= df.groupby(['candidate','year','party_detailed'],as_index=False).sum()
print(us_total_votes)

               candidate  year      party_detailed  state_fips  state_cen  \
0     ALEXANDER, STEWART  2012           SOCIALIST          59        174
1        ALLEN, JONATHAN  2008      HEARTQUAKE '08           8         84
2         AMONDSON, GENE  2004  CONCERNS OF PEOPLE           8         84
3         AMONDSON, GENE  2004         PROHIBITION          22         72
4         AMONDSON, GENE  2008         PROHIBITION          42        215
..                   ...   ...                 ...         ...        ...
496     WRIGHT, MARGARET  1976            PEOPLE'S          27         41
497  YIAMOUYIANNIS, JOHN  1992         INDEPENDENT          22         72
498  YOUNGKEIT, LOUIE G.  1988         INDEPENDENT          49         87
499       ZEIDLER, FRANK  1976           SOCIALIST         189        227
500       ZEIDLER, FRANK  1976    SOCIALIST U.S.A.          19         42

     state_ic  candidatevotes  totalvotes    version  notes
0         129            4074    16624517   60630339    0.0
1          62             348     2401361   20210113    0.0
2          62             378     2129630   20210113    0.0
3          45            1566     1943106   20210113    0.0
4         150             653    12752866   60630339    0.0
..        ...             ...         ...        ...    ...
496        33             635     1949931   20210113    0.0
497        45             808     1790017   20210113    0.0
498        67             372      647008   20210113    0.0
499       172            5399     7779637  101050565    0.0
500        31             233     1279303   20210113    0.0

[501 rows x 10 columns]

Adding a new column calculating the percentage of the popular vote gained by each candidate called <b>"percentage"</b>

In [77]:
us_total_votes['percentage']= (us_total_votes['candidatevotes']/us_total_votes['totalvotes'])*100
print(us_total_votes)

               candidate  year      party_detailed  state_fips  state_cen  \
0     ALEXANDER, STEWART  2012           SOCIALIST          59        174
1        ALLEN, JONATHAN  2008      HEARTQUAKE '08           8         84
2         AMONDSON, GENE  2004  CONCERNS OF PEOPLE           8         84
3         AMONDSON, GENE  2004         PROHIBITION          22         72
4         AMONDSON, GENE  2008         PROHIBITION          42        215
..                   ...   ...                 ...         ...        ...
496     WRIGHT, MARGARET  1976            PEOPLE'S          27         41
497  YIAMOUYIANNIS, JOHN  1992         INDEPENDENT          22         72
498  YOUNGKEIT, LOUIE G.  1988         INDEPENDENT          49         87
499       ZEIDLER, FRANK  1976           SOCIALIST         189        227
500       ZEIDLER, FRANK  1976    SOCIALIST U.S.A.          19         42

     state_ic  candidatevotes  totalvotes    version  notes  percentage
0         129            4074    16624517   60630339    0.0    0.024506
1          62             348     2401361   20210113    0.0    0.014492
2          62             378     2129630   20210113    0.0    0.017750
3          45            1566     1943106   20210113    0.0    0.080593
4         150             653    12752866   60630339    0.0    0.005120
..        ...             ...         ...        ...    ...         ...
496        33             635     1949931   20210113    0.0    0.032565
497        45             808     1790017   20210113    0.0    0.045139
498        67             372      647008   20210113    0.0    0.057495
499       172            5399     7779637  101050565    0.0    0.069399
500        31             233     1279303   20210113    0.0    0.018213

[501 rows x 11 columns]

In [78]:
us_total_votes = us_total_votes[(us_total_votes['party_detailed']== 'DEMOCRAT') | (us_total_votes['party_detailed'] == 'REPUBLICAN')]
us_total_votes.head()

,candidate,year,party_detailed,state_fips,state_cen,state_ic,candidatevotes,totalvotes,version,notes,percentage
34,"BIDEN, JOSEPH R. JR",2020,DEMOCRAT,1477,2796,2085,81268908,158528503,1030715763,0.0,51.264540
66,"BUSH, GEORGE H.W.",1988,REPUBLICAN,1477,2796,2085,48642640,91586825,1030715763,0.0,53.110958
68,"BUSH, GEORGE H.W.",1992,REPUBLICAN,1477,2796,2085,38798913,104599780,1030715763,0.0,37.092729
71,"BUSH, GEORGE W.",2000,REPUBLICAN,1477,2796,2085,50311372,105593982,1030715763,0.0,47.646060
73,"BUSH, GEORGE W.",2004,REPUBLICAN,1477,2796,2085,61872711,122349450,1030715763,0.0,50.570486

Simplifying the dataset further to only include the "candidate","party_detailed","year","candidatevotes","totalvotes","percentage" columns.

In [79]:
us_final_with_votes= us_total_votes[["candidate","party_detailed","year","candidatevotes","totalvotes","percentage"]]

In [80]:
us_final_with_votes.sort_values(['year','candidate'],inplace=True,ignore_index=True)

C:\conda_Temp\ipykernel_16608\3247746309.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  us_final_with_votes.sort_values(['year','candidate'],inplace=True,ignore_index=True)

In [81]:
us_final_with_votes

,candidate,party_detailed,year,candidatevotes,totalvotes,percentage
0,"CARTER, JIMMY",DEMOCRAT,1976,40680446,81601344,49.852667
1,"FORD, GERALD",REPUBLICAN,1976,38870893,81601344,47.635114
2,"CARTER, JIMMY",DEMOCRAT,1980,35480948,86496851,41.019930
3,"REAGAN, RONALD",REPUBLICAN,1980,43642639,86496851,50.455755
4,"MONDALE, WALTER",DEMOCRAT,1984,37449813,92654861,40.418617
5,"REAGAN, RONALD",REPUBLICAN,1984,54166829,92654861,58.460860
6,"BUSH, GEORGE H.W.",REPUBLICAN,1988,48642640,91586825,53.110958
7,"DUKAKIS, MICHAEL",DEMOCRAT,1988,41716679,91586825,45.548777
8,"BUSH, GEORGE H.W.",REPUBLICAN,1992,38798913,104599780,37.092729
9,"CLINTON, BILL",DEMOCRAT,1992,44856747,104599780,42.884170
10,"CLINTON, BILL",DEMOCRAT,1996,47295351,96389818,49.066750
11,"DOLE, ROBERT",REPUBLICAN,1996,39003697,96389818,40.464541
12,"BUSH, GEORGE W.",REPUBLICAN,2000,50311372,105593982,47.646060
13,"GORE, AL",DEMOCRAT,2000,49662314,103155297,48.143251
14,"BUSH, GEORGE W.",REPUBLICAN,2004,61872711,122349450,50.570486
15,"KERRY, JOHN",DEMOCRAT,2004,57449540,119521063,48.066457
16,OTHER,DEMOCRAT,2004,7,2384238,0.000294
17,"MCCAIN, JOHN",REPUBLICAN,2008,59613835,131419253,45.361569
18,"OBAMA, BARACK H.",DEMOCRAT,2008,69338846,131419253,52.761558
19,"OBAMA, BARACK H.",DEMOCRAT,2012,64205850,126203436,50.874883
20,"ROMNEY, MITT",REPUBLICAN,2012,60670117,129139997,46.980113
21,"CLINTON, HILLARY",DEMOCRAT,2016,65677246,139568633,47.057311
22,"TRUMP, DONALD J.",REPUBLICAN,2016,62692670,139568633,44.918882
23,"BIDEN, JOSEPH R. JR",DEMOCRAT,2020,81268908,158528503,51.264540
24,"TRUMP, DONALD J.",REPUBLICAN,2020,74216146,158528503,46.815648

In [83]:
us_final_with_votes.to_csv("election_simplified.csv",index=False)